FROM node:18.17.1
WORKDIR /app

# ホストマシンのカレントディレクトリにある package.json と package-lock.json をコピーします
# COPY package*.json ./

# 依存関係をインストールします
# RUN npm install

# ホストマシンのカレントディレクトリにあるすべてのファイルをコピーします
# COPY . .

# アプリケーションをビルドします（Viteのビルドコマンドに合わせて変更が必要かもしれません）
# RUN npm run build

# ポート 3000 でアプリケーションを公開します（必要に応じて変更してください）
EXPOSE 3000

# コンテナを実行する際に実行されるコマンドを指定します（Viteの起動コマンドに合わせて変更が必要かもしれません）
# CMD ["npm", "run", "serve"]
