version: '3'
services:
  # Railsアプリケーションのサービス
  app:
    container_name: rails-sandbox-app
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - frontend
    environment:
      DATABASE_URL: mysql2://root:password@db:3306/myapp_development # データベース接続情報

  # MySQLデータベースのサービス
  db:
    image: mysql:8.0.26
    container_name: rails-sandbox-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    ports:
      - "3306:3306"

  # Vite + Vue.js
  frontend:
    container_name: rails-sandbox-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "5173:5173"
